logging:
  level:
    root: warn
#servers:
#  - dev.bar.com
#  - foo.bar.com
#
#---
#
#spring.config.activate.on-profile: local
#kdt:
#  version: "v1.0"
#  minimum-order-amount: 1
#  support-vendors: #리스트는 바로 형변환이 안된다. 그래서 스프링부트가 제공해주는 형태로 바꿔야됨
#    - a
#    - b
#    - c
#    - d
#  description: | #|- 이렇게하면 마지막 줄바꿈이 제외됨
#    line 1 hello world
#    line2 xxxx
#    line 3
##그룹화하기 위해서 많이 사용함. 큰 프로젝트에서 씀. 속성이 다양하기 때문에 그룹화를 먼저 함.
#
#
#---
##한 파일에 여러가지 property를 적을 수 있음. 맨 위에있는걸로 호출 가능하다.
#spring.config.activate.on-profile: dev
#kdt:
#  version: "v1.0.5"
#  minimum-order-amount: 3
#  support-vendors: #리스트는 바로 형변환이 안된다. 그래서 스프링부트가 제공해주는 형태로 바꿔야됨
#    - dev-a
#    - dev-b
#    - dev-c
#    - dev-d
#  description: | #|- 이렇게하면 마지막 줄바꿈이 제외됨
#    dev-line 1 hello world
#    dev-line2 xxxx
#    dev-line 3
##그룹화하기 위해서 많이 사용함. 큰 프로젝트에서 씀. 속성이 다양하기 때문에 그룹화를 먼저 함.


kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors: #리스트는 바로 형변환이 안된다. 그래서 스프링부트가 제공해주는 형태로 바꿔야됨
    - default-a
    - default-b
    - default-c
    - default-d
  description: | #|- 이렇게하면 마지막 줄바꿈이 제외됨
    default- line 1 hello world
    default- line2 xxxx
    default- line 3